dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: RAF Raw Airborne Data System (ADS) Data
- summary: RAF aircraft gather raw data which are recorded onto removable hard disk drives by an on-board data system (ADS). These data are saved as one file per flight. This dataset contains these ADS data files. Following the projects field phase, these raw data are processed using the RAF-developed NIMBUS software to produce 'production' data (with calibrated values in engineering units) having the highest-quality that RAF can provide. These calibrated data are provided as a separate dataset. \n\nADS data should NOT be distributed to the public. They are entered into CODIAC for tracking purposes only!
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '1.0'
- quality: 2
- ingest_location: /scr/raf/Raw_Data/<PROJECT>
- archive_location: /FS/EOL/<year>/<project>/aircraft/c130_n130ar/ADS
- filename_pattern: '[\Y\Y\Y\Y\M\M\y\y]_[\H\H\m\m\S\S]_(\E\E\E\E).ads'
- startdate_pattern: YYYY-MM-yy HH:mm:SS
- enddate_pattern: ''
- filelength: 6 hours
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: 118
- host: hpss
- frequency_id: 3
- spatial_type: multiple
- point_of_contact_id_codiac: 1
- internal_contact_id_codiac: 179
- online_orderable: 0
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 0
- event_subset: 1
- order_allow_compress: 1
- DTS_specific_fields: titleSep
- source_contact_id_dts: 203
- internal_contact_id_dts: 203
- ingest_contact_id_dts: 348
- ingest_status_id_dts: 2
- load_contact_id_dts: 345
- load_data_location: '*ads'
- load_status_id_dts: 6
- approve_contact_id_dts: 345
- approve_status_id_dts: 6
- author_id_dts: 203
- note_type_id: 4
- note_text: Loaded with new load_data_proj script. \n\nADS data should NOT be distributed to the public. They are entered into CODIAC for tracking purposes only!
- optional_fields: titleSep
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- format_2: null
- host_2: null
- description: 'default'
- iso_citation_role: 11
- contact_id_codiac: 1001
- datacite_contributor_type: null
- iso_citation_role_2: 10
- contact_id_codiac_2: 1001
- datacite_contributor_type_2: null
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
- readme_url: 'default'
- remote_url: 'default'
