dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: FO3 (Fast Ozone) High Rate Data
- summary: This data set contains ozone by chemiluminescent reaction with excess NO collected aboard the NSF/NCAR C-130 during <PROJECT>.  This data set is in ICARTT format. Please see the header portion of the data files for details on instruments, parameters, quality assurance, quality control, contact information, and data set comments.
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 0
- eula_reqd: 0
- version_number: '1.0'
- quality: ''
- ingest_location: /scr/raf/Prod_Data/<PROJECT>/O3
- archive_location: /glade/campaign/eol/archive/<year>/<project>/aircraft/c130_n130ar/O3
- filename_pattern: <project>-high_rate_O3_C130_[\Y\Y\Y\Y\M\M\y\y]_<VERSION>.ict
- startdate_pattern: YYYY-MM-yy 00:00:00
- enddate_pattern: ''
- filelength: 6 hours
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: 152
- host: campaign
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: ''
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 1
- event_subset: 0
- file_subset: 0
- order_allow_compress: 1
- gcmd_science_keyword_id: 362
- xlink_id:
- DTS_specific_fields: titleSep
- source_contact_id_dts: 
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts: 
- load_data_location: '*ict'
- load_status_id_dts: 6
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 4
- note_text: Loaded with new load_data_proj script.
- readme_url: 'default'
- remote_url: 'default'
- optional_fields: titleSep
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: ''
- host_2: ''
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: ''
- host_3: ''
- description: 'default'
- iso_citation_role: 2
- contact_id_codiac: 1001
- datacite_contributor_type: ''
- iso_citation_role_2: 8
- contact_id_codiac_2: 238
- datacite_contributor_type_2: ''
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
