dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: CO2COCH4H20 - PICARRO G2401-m WS-CRDS in situ mixing ratio for Carbon dioxide (CO2), carbon monoxide (CO), Methane (CH4), and water vapor (H2O) data
- summary: This dataset contains high rate (< 1sps) carbon dioxide (CO2), carbon monoxide (CO), water vapor, and methane (CH4) in situ mixing ratio observations collected by the PICARRO G2401-m aboard the NSF/NCAR HIAPER GV during the <PROJECT> project.
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '1.0'
- quality: 2
- ingest_location: /scr/raf/Prod_Data/<PROJECT>
- archive_location: /glade/campaign/eol/archive/<year>/<project>/aircraft/gv_n677f/CO2COCH4
- filename_pattern: <project>-CO2COCH4H2O_PIC_GV_[\Y\Y\Y\Y\M\M\y\y]_R*.ict
- startdate_pattern: YYYY-MM-yy 00:00:00
- enddate_pattern: 
- filelength: 6 hours
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 350
- is_eol_data: 1
- format: 152
- host: campaign
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: 1
- internal_contact_id_codiac: 3624
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 1
- event_subset: 0
- file_subset: 0
- order_allow_compress: 1
- gcmd_science_keyword_id: 318, 324
- xlink_id:
- DTS_specific_fields: titleSep
- source_contact_id_dts: 203 
- internal_contact_id_dts: 366
- ingest_contact_id_dts: 203
- ingest_status_id_dts: 2
- load_contact_id_dts: 366
- load_data_location: '*ict'
- load_status_id_dts: 6
- approve_contact_id_dts: 203
- approve_status_id_dts: 6
- author_id_dts: 366
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- readme_url: 'default'
- remote_url: 'default'
- optional_fields: titleSep
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: null
- host_2: null
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3:  ''
- host_3:  ''
- description: 'default'
- iso_citation_role: 2
- contact_id_codiac: 179
- datacite_contributor_type: 4
- iso_citation_role_2: 9
- contact_id_codiac_2: 238
- datacite_contributor_type_2: 2
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
