dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: Low Rate (LRT - 1 sps) Navigation, State Parameter, and Microphysics Flight-Level Data
- summary: This data set includes airborne measurements obtained from the NSF/NCAR HIAPER GV aircraft (Tail Number N677F) during the <PROJECT> project. This dataset contains low rate navigation, state parameter, and microphysics flight-level data in netCDF format.
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '1.0'
- quality: 2
- ingest_location: /scr/raf/Prod_Data/<PROJECT>/LRT/version1_0
- archive_location: /net/archive/data/<project>/aircraft/gv_n677f/LRT/version1_0
- filename_pattern: (\E\E\E\E).(\Y\Y\Y\Y\M\M\y\y).[\H\H\m\m\S\S]_{\H\H\m\m\S\S}.PNI.nc
- startdate_pattern: YYYY-MM-yy HH:mm:SS
- enddate_pattern: YYYY-MM-yy HH:mm:SS
- filelength: ''
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 350
- is_eol_data: 1
- format: 46
- host: localhost
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: 1
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 0
- event_subset: 1
- file_subset: 0
- order_allow_compress: 1
- gcmd_science_keyword_id: 380, 450, 473, 505, 491, 451, 463, 476, 3077, 404, 516, 3034, 413, 391, 480, 3071, 3039, 483, 460, 470
- xlink_id: 6223, 3427
- DTS_specific_fields: titleSep
- source_contact_id_dts: 203
- internal_contact_id_dts: 203
- ingest_contact_id_dts: 203
- ingest_status_id_dts: 2
- load_contact_id_dts: 203
- load_data_location: '*nc'
- load_status_id_dts: 6
- approve_contact_id_dts: 203
- approve_status_id_dts: 6
- author_id_dts: 203
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- readme_url: 'N/A'
- remote_url: 'N/A'
- optional_fields: titleSep
- instrument_id: ''
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: null
- host_2: null
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: null
- host_3: null
- description: 'default'
- iso_citation_role: 11
- contact_id_codiac: 1001
- datacite_contributor_type: ''
- iso_citation_role_2: 10
- contact_id_codiac_2: 1001
- datacite_contributor_type_2: ''
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
