dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: Small Ice Detector Version 2 (SID-2H) data
- summary: This dataset contains SID2H data collected during the <PROJECT> project. The Small Ice Detector, Version 2 (SID2H) is a particle light-scattering instrument for measuring size distributions of particles in the 1 to 70 micrometer size range and for discriminating between ice crystals and supercooled water droplets in mixed phase clouds. SID2H measures the intensity of light scattered by cloud particles in the forward direction. Measurements are recorded for each particle that crosses the instrument's laser beam. The SID2H data files are binary and come in 10-minute blocks; a new file is created every 10 minutes. Data records include timing events, light scattering intensity, and housekeeping (temperatures, laser power, etc.). The file structure has a header, data, and a footer. There is a detailed description in the document SID2 Software Interface.pdf pages 26-29 and 67-75, accessible via the link below.
- begin_date: '1000-01-01 00:00:00'
- end_date: '7999-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 0
- version_number: '0.1'
- quality: 1
- ingest_location: /scr/raf/Raw_Data/<PROJECT>/sid2h
- archive_location: /glade/campaign/eol/archive/<year>/<project>/aircraft/gv_n677f/SID2H
- filename_pattern: sids_(\E\E\E\E).dat
- startdate_pattern: '1000-01-01 00:00:00'
- enddate_pattern: '7999-12-31 23:59:59'
- filelength: ''
- minimum_latitude: '-90'
- maximum_latitude: '90'
- minimum_longitude: '-180'
- maximum_longitude: '180'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 350
- is_eol_data: 1
- format: 75
- host: campaign
- frequency_id: 1
- spatial_type: point
- point_of_contact_id_codiac: 1
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 0
- event_subset: 1
- file_subset: 0
- order_allow_compress: 1
- gcmd_science_keyword_id: 287, 506, 614
- xlink_id:
- DTS_specific_fields: titleSep
- source_contact_id_dts: 
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts:
- load_data_location: '*dat'
- load_status_id_dts: 3
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 4
- note_text: Loaded by load_data_proj scripts
- readme_url: 'default'
- remote_url: 'default'
- optional_fields: titleSep
- instrument_id: 76
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: ''
- host_2: ''
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: ''
- host_3: ''
- description: 'description'
- iso_citation_role: 11
- contact_id_codiac: 729
- datacite_contributor_type: ''
- iso_citation_role_2: 10
- contact_id_codiac_2: 1001
- datacite_contributor_type_2: ''
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
