dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: Airborne Oxygen Instrument (AO2)
- summary: The NCAR Airborne Oxygen Instrument (AO2) was mounted on the NCAR GV during the <PROJECT> project. The submitted AO2 data are in 1 flat ascii text file per flight. Each file contains running 1-Second interpolated values (of the original ~ 2.5-second data) at 1 Hz matching the times in the RAF data files. The files are in NASA Ames 1001 format, with a final comment line of variable names (UT, CO2_AO2, O2_AO2, O2_AO2ADJ, and APO_AO2ADJ), spaces separating columns, and 9999.99 for missing data. The reported times correspond to when the air entered the inlet. This instrument measures O2/N2 ratio as well as CO2 concentration.
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '0.1'
- quality: 1
- ingest_location: /scr/raf/Raw_Data/<PROJECT>/field_phase/quicklook/(\E\E\E\E)
- archive_location: /glade/campaign/eol/archive/<year>/<project>/aircraft/c130_n130ar/field_phase/quicklook/(\E\E\E\E)
- filename_pattern: AO2_[\Y\Y\Y\Y\M\M\y\y]_(\E\E\E\E)_quicklook.GV
- startdate_pattern: YYYY-MM-yy 00:00:00
- enddate_pattern: ''
- filelength: 6 hours
- minimum_latitude: '90.0'
- maximum_latitude: '-90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: 146
- host: campaign
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: ''
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 0
- event_subset: 1
- file_subset: 0
- order_allow_compress: 1
- gcmd_science_keyword_id: 318, 361
- xlink_id:
- DTS_specific_fields: titleSep
- source_contact_id_dts: 
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts: 
- load_data_location: AO2*
- load_status_id_dts: 6
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- readme_url: 'default'
- remote_url: 'default'
- optional_fields: titleSep
- instrument_id: ''
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: ''
- host_2: ''
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: ''
- host_3: ''
- description: 'default'
- iso_citation_role: 11
- contact_id_codiac: 1001
- datacite_contributor_type: ''
- iso_citation_role_2: 10
- contact_id_codiac_2: 1001
- datacite_contributor_type_2: ''
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
