dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: Quantum Cascade Laser Spectrometer DUAL CO CH4 N2O
- summary: The Quantum Cascade Laser Spectrometer DUAL measured CO, CH4, and N2O concentrations in situ aboard the NSF/NCAR GV during <PROJECT>. This dataset contains CO_QCLS, CH4_QCLS, N2O_QCLS data in NASA Ames format collected during <PROJECT>.
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '0.1'
- quality: 1
- ingest_location: /scr/raf/Raw_Data/<PROJECT>/field_phase/quicklook/(\E\E\E\E)
- archive_location: /glade/campaign/eol/archive/<year>/<project>/aircraft/c130_n130ar/field_phase/quicklook/(\E\E\E\E)
- filename_pattern: CH4-N2O-CO-QCLS_[\Y\Y\Y\Y\M\M\y\y]_(\E\E\E\E).GV
- startdate_pattern: YYYY-MM-yy 00:00:00
- enddate_pattern: ''
- filelength: 6 hours
- minimum_latitude: '90.0'
- maximum_latitude: '-90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: 116
- host: campaign
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: ''
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 0
- event_subset: 1
- file_subset: 0
- order_allow_compress: 1
- gcmd_science_keyword_id: 319, 324, 358
- xlink_id:
- DTS_specific_fields: titleSep
- source_contact_id_dts: 
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts: 
- load_data_location: CH4-NO2-CO-QCLS*
- load_status_id_dts: 6
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- readme_url: 'default'
- remote_url: 'default'
- optional_fields: titleSep
- instrument_id: ''
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: ''
- host_2: ''
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: ''
- host_3: ''
- description: 'default'
- iso_citation_role: 11
- contact_id_codiac: 1513
- datacite_contributor_type: ''
- iso_citation_role_2: 10
- contact_id_codiac_2: 1001
- datacite_contributor_type_2: ''
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
