dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: Low Rate (LRT - 1 sps) Navigation, State Parameter, and Microphysics Flight-Level Data - ICARTT format
- summary: This data set includes airborne measurements obtained from the NSF/NCAR C-130 aircraft (Tail Number N130AR) during the <PROJECT> project. This dataset contains low rate navigation, state parameter, and microphysics flight-level data in ICARTT format.
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '0.1'
- quality: 1
- ingest_location: /scr/raf/Raw_Data/<PROJECT>/LRT/icartt
- archive_location: /glade/campaign/eol/archive/<year>/<project>/aircraft/c130_n130ar/field_phase/LRT/ICARTT
- filename_pattern: <PROJECT>-RAF-<category>_C130_[\Y\Y\Y\Y\M\M\y\y]_R*.ict
- startdate_pattern: YYYY-MM-yy 00:00:00
- enddate_pattern: YYYY-MM-yy 23:59:59
- filelength: ''
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: 152
- host: campaign
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: ''
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 1
- event_subset: 0
- file_subset: 0
- order_allow_compress: 1
- gcmd_science_keyword_id: 380, 450, 473, 505, 491, 451, 463, 476, 3077, 404, 516, 3034, 413, 391, 480, 3071, 3039, 483, 460, 470
- xlink_id: 6223
- DTS_specific_fields: titleSep
- source_contact_id_dts: 
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts: 
- load_data_location: '*ict'
- load_status_id_dts: 6
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- readme_url: 'default'
- remote_url: 'default'
- optional_fields: titleSep
- instrument_id: ''
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: ''
- host_2: ''
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: ''
- host_3: ''
- description: 'default'
- iso_citation_role: 11
- contact_id_codiac: 1001
- datacite_contributor_type: ''
- iso_citation_role_2: 10
- contact_id_codiac_2: 1001
- datacite_contributor_type_2: ''
- iso_citation_role_3: 1
- contact_id_codiac_3: ''
- datacite_contributor_type_3: ''
- iso_citation_role_4: ''
- contact_id_codiac_4: ''
- datacite_contributor_type_4: ''
- iso_citation_role_5: ''
- contact_id_codiac_5: ''
- datacite_contributor_type_5: ''
