dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: PRELIMINARY Low Rate (LRT - 1 sps) Navigation, State Parameter, and Microphysics Flight-Level Data - IWG1 format
- summary: This data set includes airborne measurements obtained from the NSF/NCAR C-130 aircraft (Tail Number N130AR) during the <PROJECT> project. This dataset contains low rate navigation, state parameter, and microphysics flight-level data in IWG1 format. These are PRELIMINARY FIELD-PHASE data and are not for publication. Final, production data (with calibrated values in engineering units) having the highest-quality that RAF can provide will be available within 6 months of the end of the project.
- begin_date: '1001-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '0.1'
- quality: 1
- ingest_location: /scr/raf/Raw_Data/<PROJECT>/field_sync/EOL_data/RAF_data/IWGI
- archive_location: /glade/campaign/eol/archive/<year>/<project>/aircraft/c130_n130ar/FIELD/IWG1
- filename_pattern: <PROJECT>(\E\E\E\E).iwg
- startdate_pattern: YYYY-MM-yy HH:mm:SS
- enddate_pattern: YYYY-MM-yy HH:mm:SS
- filelength: ''
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: 166
- host: hpss
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: 1
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 0
- file_subset: 0
- event_subset: 1
- order_allow_compress: 1
- DTS_specific_fields: titleSep
- source_contact_id_dts: 
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts: 
- load_data_location: '*iwg'
- load_status_id_dts: 6
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- optional_fields: titleSep
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- format_2: ''
- host_2: ''
- description: ''
- iso_citation_role: ''
- contact_id_codiac: ''
- datacite_contributor_type: ''
- iso_citation_role_2: ''
- contact_id_codiac_2: ''
- datacite_contributor_type_2: ''
