datacite_contributor_type:
  1: Contactperson
  2: DataCollector
  3: DataCurator
  4: DataManager
  5: Distributor
  6: Editor
  7: Funder
  8: HostingInstitution
  9: Producer
  10: ProjectLeader
  11: ProjectManager
  12: ProjectMember
  13: RegistrationAgency
  14: RegistrationAuthority
  15: RelatedPerson
  16: Researcher
  17: ResearchGroup
  18: RightsHolder
  19: Sponsor
  20: Supervisor
  21: WorkPackageLeader
  22: Other
