dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: RAL Raw 2DS
- summary: The 2DS captures two-dimensional images of particles passing through the sample volume where laser beams overlap. Two 128-photodiode linear arrays work independently as high-speed and high-resolution optical imaging probes. The region where the beams overlap uniquely defines the depth-of-field (and thus the sample volume) for small particles. The 2DS measures particles from 10 to 1280 microns at a 10 micron resolution.
- begin_date: '1000-01-01 00:00:00'
- end_date: '7999-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '0.1'
- quality: 1
- ingest_location: /scr/raf/Raw_Data/<PROJECT>/2DS
- archive_location: /FS/EOL/<year>/<project>/aircraft/c130_n130ar/2DS
- filename_pattern: (\E\E\E\E)/base[\Y\Y\M\M\D\D\h\h\m\m\S\S].2DS
- startdate_pattern: 20YY-MM-DD HH:MM:ss
- enddate_pattern: ''
- filelength: 6 hours
- minimum_latitude: '-90'
- maximum_latitude: '90'
- minimum_longitude: '-180'
- maximum_longitude: '180'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: ''
- host: hpss
- frequency_id: 2
- spatial_type: raster
- point_of_contact_id_codiac: ''
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 0
- event_subset: 1
- file_subset: 0
- order_allow_compress: 1
- DTS_specific_fields: titleSep
- source_contact_id_dts: ''
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts: 
- load_data_location: '*'
- load_status_id_dts: 6
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 2
- note_text: This dataset loaded with the insert_proj_dataset script.
- optional_fields: titleSep
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: ''
- host_2: ''
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: ''
- host_3: ''
- description: ''
- iso_citation_role: ''
- contact_id_codiac: ''
- datacite_contributor_type: ''
- iso_citation_role_2: ''
- contact_id_codiac_2: ''
- datacite_contributor_type_2: ''
