dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: 5 minute ISFS data, tilt corrected
- summary: This dataset contains 5 minute ISFS data. These data are in NetCDF format, and have been tilt corrected.
- begin_date: '1002-01-01 00:00:00'
- end_date: '7999-12-31 23:59:59'
- visible: 0
- auth_reqd: 0
- eula_reqd: 0
- version_number: '1.0'
- quality: 2
- ingest_location: /net/data/archive/<PROJECT>/surface/netcdf_5min/tc
- archive_location: /FS/EOL/<year>/<project>/surface/isfs/netcdf_5min/tc
- filename_pattern: isfs_tc_(\Y\Y\Y\Y\M\M\y\y).nc
- startdate_pattern: YYYY-MM-yy 00:00:00
- enddate_pattern: YYYY-MM-yy 23:59:59
- filelength: ''
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 18
- platform_id: 453
- is_eol_data: 1
- format: 130
- host: hpss
- frequency_id: 11
- spatial_type: unknown
- point_of_contact_id_codiac: 687
- internal_contact_id_codiac: 328
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 1
- event_subset: 0
- file_subset: 0
- order_allow_compress: 1
- DTS_specific_fields: titleSep
- source_contact_id_dts: 
- internal_contact_id_dts: 
- ingest_contact_id_dts: 
- ingest_status_id_dts: 2
- load_contact_id_dts: 
- load_data_location: '*nc'
- load_status_id_dts: 6
- approve_contact_id_dts: 
- approve_status_id_dts: 6
- author_id_dts: 
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- readme_url: 'default'
- remote_url: 'default'
- optional_fields: titleSep
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- filelength_2: ''
- format_2: ''
- host_2: ''
- archive_location_3: ''
- filename_pattern_3: ''
- startdate_pattern_3: ''
- enddate_pattern_3: ''
- filelength_3: ''
- format_3: ''
- host_3: ''
- description: ''
- iso_citation_role: ''
- contact_id_codiac: ''
- datacite_contributor_type: ''
- iso_citation_role_2: ''
- contact_id_codiac_2: ''
- datacite_contributor_type_2: ''
