category_id:
   1001: EOL Data Support
   1: Aerosol
   2: Aircraft
   3: Ancillary Info
   4: Chemistry
   5: Ecology
   6: Electrification
   7: Hydrology
   8: Ice Physics
   9: Land Character
   10: Lidar
   11: Models/Analyses
   13: Oceanography
   14: Radar
   15: Satellite
   16: Sounding
   17: Sub-Surface
   18: Surface
   19: Upper Air
   20: Photography
   21: Arctic
   22: Biology
   23: Operational Products
   24: Research Products
   25: Reports
   26: Satellite Products
   27: GIS Display Products
   28: Upper Air Products
   29: Operational Surface Products
   30: Radar Products
   31: Lightning Products
   32: Weather Text Products
   33: NCEP GFS Forecast Products
   34: NCEP NAM Forecast Products
   35: NCEP RAP Forecast Products
   36: NCAR WRF ARW Forecast Products
   37: Aircraft Products
   38: Upper Air Products
   39: Other Products
   40: NCAR WRF GFS Forecast Products
   41: ESRL HRRR Forecast Products
   42: CSU WRF Forecast Products
   43: All report products
   44: Air Quality Products
   45: Mozart4 Chemical Forecast Products
   46: NASA GEOS5 Chemical Forecast Products
   47: ESRL HRRR Dev Forecast Products
   48: ESRL RAP Forecast Products
   49: ESRL RAP Dev Forecast Products
   50: Georgia Tech WRF-CMAQ Forecast Products
   51: SOAS Centreville Alabama Site Products
   52: FLEXPART Chemical Forecast Products
   53: SOAS National Weather Service Site Products
   54: SOAS Alabama Aquatic Biodiversity Center (AABC) Site
   55: University of Alabama-Huntsville Site Products
   56: GEOS Chem NRT Simulation Products
   57: GFS Forecast Products
   58: US Navy COAMPS Adjoint Forecast Products
   59: ECMWF IFS Forecast Products
   60: US Navy COAMPS 15km Forecast Products
   61: NCAR WRF Ensemble Forecast Products
   62: SUNY-OSW WRF Forecast Products
   63: NCEP NAM-HIRES Forecast Products
   64: Radar Products
   65: SUNY-OSW WRF RAP Init Forecast Products
   66: Discussions
   67: Summaries
   68: NCEP Fire Wx NAM Forecast Products
   69: ALPHA Nowcast Products
   70: ACCESS-R Forecast Products
   71: Research Surface Products
   72: Status reports
   73: Wyoming Facilities
   74: CSWR Facilities
   75: UIUC Facilities
   76: SUNY Facilities
   77: HWSmith Facilities
   78: Univ of Alabama Facilities
   79: Millersville University Facilities
   80: Univ of Utah Facilities
   81: US Navy NAVGEM Forecast Products
   82: MJO Products
   83: Observations
   84: Taiwan CWB WRF ARW Forecast Products
   85: WAFC Aviation Forecast Products
   86: CIMSS RAQMS 1x1 Degree Forecast Products
   87: Aircraft and state parameters
   88: Dew point and humidity
   89: Radiometers
   90: Chemistry
   91: Wing stores
   92: NCAR/MMM WRF ARW 3km Forecast Products
   93: NCEP GFS ACD UTLS Forecast Products
   94: NCAR/MMM WRF ARW 15km Forecast Products
   95: MACC Forecast Products
   96: NCAR/ACD CAMChem 2 Degree Forecast Products
   97: Briefing Input
   98: Forecast Input
   99: NCAR/ACD CAMChem 1 Degree Forecast Products
   100: Briefings
   101: Ops Plans
   102: Ops Summaries
   103: Operations
   104: University of Cambridge NAME Forecast Products
   105: General
   106: Cloud Particle Microphysics
   107: Bulk Microphysics
   108: Remote Sensing
   109: State Parameters
   110: Electro-static Field
   111: Imaging
   112: NCEP GEFS Forecast Products
   113: Radar Products
   114: Surface Products
   115: Satellite Products
   116: Sounding Products
   117: Environmental Advisories
   118: Air Quality
   119: Climate Advisories
   120: Dust/Ash Advisories
   121: Frost/Freeze Warning
   122: Heat Advisory
   123: Present Weather
   124: Severe Weather
   125: UV Radiation
   126: Weather Forecast
   127: Charts
   128: Analysis
   129: Mesoanalyses
   130: NSSL WRF Forecast Products
   131: Advisory Products
   132: University of Innsbruck WRF Forecast Products
   133: NCAR Aircraft
   134: DLR Aircraft
   135: Hokitika Site
   136: Haast Site
   137: Lauder Site
   138: Hobart Site
   140: Mt. John Site
   141: Davis Site
   142: Model Analyses
   143: Model Analyses
   144: Surface Observation Products
   145: Time-Height Plots
   147: CAPS Ensemble Forecast Products
   149: NIWA N320L50 Forecast Products
   150: NIWA N768L70 Forecast Products
   151: NIWA NZCSM Forecast Products
   152: NIWA NZLAM-12 Forecast Products
   153: Macquarie Island Site
   154: US Navy COAMPS 5km Forecast Products
   155: ESRL RAPChem 13km Forecast Products
   156: NCAR STEP WRF ARW 3km Forecast Products
   157: NCAR FLEXPART 4km Forecast Products
   158: Fixed Ground Sites
   159: Mobile Ground Systems
   161: NOAA CMAQ 4km Forecast Products
   163: Remote Sensing Products
   164: Planning
   165: US Navy NAAPS Aerosol Forecast Products
   166: UW FLEXPART Forecast Products
   167: NOAA NAQFC Forecast Products
   169: Lidar products
   170: ALPHA Nowcast Products
   171: NCEP HRRR Forecast Products
   172: Mobile PISA
   173: Mobile Radiosonde
   174: Fixed PISA
   175: Mobile Surface In Situ
   176: Mobile Remote Sensing
   177: Fixed Radar
   178: NOAA Aircraft
   179: Univ Wyoming Aircraft
   180: NASA Aircraft
   181: Warning Products
   182: Fixed PISA Lidar Products
   183: OU MAP WRF Ensemble Mean Forecast Products
   184: OU MAP WRF Ensemble Probability Forecast Products
   185: OU MAP WRF Ensemble Spaghetti Forecast Products
   186: OU MAP WRF 1km Deterministic Forecast Products
   187: Photography Products
   188: Fixed PISA Surface Products
   189: Mobile PISA Surface Products
   191: Fixed Research Radar Products
   192: Mobile Research Radar Products
   194: Fixed PISA Upper Air Products
   195: Mobile PISA Upper Air Products
   196: Mosaic Products
   197: UMBC-HU NWS Site Lidar Products
   198: NCAR MPAS 15-3km Forecast Products
   199: NSSL WRF Ensemble Forecast Products
   200: UMBC-HU Fixed Radar Site Lidar Products
   201: Mobile PISA Lidar Products
   202: Airborne Radar Products
   203: University of Washington HYSPLIT-GFS Forecast Products
   204: Dropsonde Products
   205: Plots
   206: Flight tracks
   207: CMC GEM Forecast Products
   208: Polar Orbiting Satellite Products
   209: Geostationary Satellite Products
   210: Low Earth Orbit Satellite Products
   211: NWS 88-D Atlantic Coast Site Radar Products
   212: NWS 88-D Gulf of Mexico Site Radar Products
   213: Other International Site Radar Products
   214: NCEP HWRF Forecast Products
   215: Airmass Analyses
   218: GFDL Forecast Products
   219: US Navy COAMPS TC-specific Forecast Products
   220: National Hurricane Center Products
   222: National Hurricane Center Products
   223: ECMWF Ensemble Forecast Products
   224: SHOUT Reports
   225: NCAR AMPS 9km Forecast Products
   226: NCAR AMPS 27km Forecast Products
   227: US Navy COAMPS TC-specific Ensemble Forecast Products
   228: COAMPS-TC, GFDL, HWRF Multi-Model Ensemble Forecast Products
   229: GFDL Ensemble Forecast Products
   230: NCEP HWRF Ensemble Forecast Products
   231: Antarctic
   232: Univ of Michigan STILT Forecast Products
   233: NCAR/CGD CESM CAM-SD Fully Coupled Forecast Products
   235: Ship
   236: Ship observations
   237: NCAR/CGD CESM CAM-SD Movie Loops
   238: Lightning Products
   240: Mobile Sounding Products
   241: UW FLEXPART Trajectory Forecast Products
   242: Trajectories
   243: Fire Products
   244: NCEP NAM 4km Forecast Products
   245: UW WRF-GFS 4km Forecast Products
   246: UAZ WRF-NAM 1.8km Forecast Products
   247: NASA Facilities
   248: IPC Facilities
   249: CU Facilities
   250: NCAR Facilities
   251: WMI Facilities
   252: Research Products
   253: IPC Aircraft
   254: Research Sounding Products
   255: Aviation Advisories
   256: IPMA AROME Forecast Products
   257: BoM ACCESS Forecast Products
   258: NCEP CFS Forecast Products
   259: TTU Facilities
   260: OU Facilities
   261: UMass Facilities
   262: Purdue Facilities
   263: UAH Facilities
   264: NOAA/ATDD Facilities
   265: NOAA/NSSL Facilities
   266: ULM Facilities
   267: MSU Facilities
   268: CSU Facilities
   269: NOAA HRRR Ensemble Forecast Products
   270: North American Ensemble Forecast System Products
   271: SASSI
   272: Tower
   273: Scanning Lidar
   274: Profiling Lidar
   275: Profiler
   276: Special
   277: Ceilometer Products
   278: NOAA HRRR-Smoke Forecast Products
   279: Environment Canada NWSM Forecast Products
   280: NRL ICAP Ensemble Forecast Products
   281: WSU AIRPACT-5 Forecast Products
   282: USFS Blue Sky Forecast Products
   283: INMET COSMO 7km Forecast Products
   284: NCEP GEFS Argentina Forecast Products
   285: ECMWF Forecast Products
   286: UIUC GFS-WRF Forecast Products
   287: RSV Aurora Australis Products
   288: FNMOC Wave Watch 3 Forecast Products
   289: Shipborne Radar Products
   290: Shipborne Sounding Products
   291: Shipborne Surface Products
   292: NASA LaRC SATCORPS
   293: RV Investigator Products
   294: NASA LaRC HIMAWARI-8 Imagery
 