dts_contact_id_active:
   103: kbeierle
   193: anstett
   197: dstott
   201: gstoss
   203: jaquino
   205: jja
   207: jmoore
   209: lcully
   210: local
   221: sloehrer
   222: swilliams
   238: snorman
   256: lechohawk
   276: cbsnyder
   327: mpaulus
   328: jblomer
   332: reichlin
   336: heechang
   337: patnam
   338: connell
   340: arobinso
   343: uromatschke
   345: taylort
 