format:
   1001: EOL Data Support
   10: E-BUFR
   18: QCF
   22: NetCDF
   30: GRIB
   34: GIF
   37: BUFR
   42: CD-ROM
   43: ASCII
   44: GIF
   51: ZIP
   53: TAR
   60: JPEG
   67: XLS
   68: PDF
   69: HDF
   79: TIFF
   82: PNG
   83: HTML
   88: QCF1.0
   89: QCF1.1
   90: QCF1.2
   91: QCF2.0
   92: QCF2.1
   93: QCF3.0
   94: QCF3.1
   95: QCF3.2
   96: QCF4.0
   102: GRIB-1
   103: GRIB-2
   104: HDF4
   105: HDF5
   108: wmv
   109: MPEG
   110: MOV
   111: gmeta
   112: EDGEzip
   113: kml
   114: kmz
   115: XML
   117: SPSS
   118: ADS
   119: AVI
   120: DORADE
   121: CDFtar
   122: CfRad
   124: GDB
   126: BMP
   127: MP4
   128: DIF
   129: 7z
   130: NetCDF
   131: CSV
   133: MRR
   135: SHP
   136: SHX
   137: DBF
   138: PRJ
   139: SBN
   142: WMF
   143: AREA
   144: SYN
   145: METAR
   146: ASCII
   147: DAT
   148: RINEX
   150: RTF
   152: ICT
   153: WAV
   154: CTD
   155: EPS
   156: WebM
   157: Ogg
   164: JSON
   166: IWG1
   174: MTS
   180: BADCCSV
   181: Enex
   182: RAW
   190: 2D-S
 