frequency_id:
   1001: EOL Data Support
   1: unknown
   2: continuous
   3: < 1 second
   4: 1 second
   5: < 1 minute
   6: 1 minute
   7: 90 second
   8: 2 minute
   9: 3 minute
   10: 4 minute
   11: 5 minute
   12: 6 minute
   13: 7 minute
   14: 8 minute
   15: 9 minute
   16: 10 minute
   17: 12 minute
   18: 15 minute
   19: 20 minute
   20: 30 minute
   21: 40 minute
   22: 50 minute
   23: hourly
   24: 90 minute
   25: 2 hourly
   26: 3 hourly
   27: 4 hourly
   28: 6 hourly
   29: 8 hourly
   30: 12 hourly
   31: daily
   32: weekly
   33: monthly
   34: criteria
   35: no set schedule
   36: other
   37: 70 or 140 sec
   38: 10 second
 