iso_citation_rule:
  1: resourceProvider
  2: custodian
  3: owner
  4: user
  5: distributor
  6: originator
  7: pointOfContact
  8: principalInvestigator
  9: processor
  10: publisher
  11: author
  12: EOL_internal
