dataset:
- title_content: titleSep
- name: <PROJECT>
- archive_ident: '999.999'
- title: High Rate (HRT - 25 sps) Navigation, State Parameter, and Microphysics Flight-Level Data - ICARTT format
- summary: This data set includes airborne measurements obtained from the NSF/NCAR C-130 aircraft (Tail Number N130AR) during the <PROJECT> project. This dataset contains high rate navigation, state parameter, and microphysics flight-level data in ICARTT format.
- begin_date: '1010-01-01 00:00:00'
- end_date: '7998-12-31 23:59:59'
- visible: 0
- auth_reqd: 1
- eula_reqd: 1
- version_number: '1.0'
- quality: 2
- ingest_location: /scr/raf/Prod_Data/<PROJECT>/ICARTT_format
- archive_location: /FS/EOL/<year>/<project>/aircraft/c130_n130ar/FIELD/HRT/ICARTT
- filename_pattern: <PROJECT>-RAF-<category>_C130_[\Y\Y\Y\Y\M\M\y\y]_R*.ict
- startdate_pattern: YYYY-MM-yy 00:00:00
- enddate_pattern: 
- filelength: 6 hours
- minimum_latitude: '-90.0'
- maximum_latitude: '90.0'
- minimum_longitude: '-180.0'
- maximum_longitude: '180.0'
- CODIAC_specific_fields: titleSep
- category_id: 2
- platform_id: 130
- is_eol_data: 1
- format: 152
- host: hpss
- frequency_id: 4
- spatial_type: point
- point_of_contact_id_codiac: 1
- internal_contact_id_codiac: 179
- online_orderable: 1
- offline_orderable: 0
- browseable: 0
- dodsable: 0
- t_subset: 1
- event_subset: 0
- file_subset: 0
- order_allow_compress: 1
- DTS_specific_fields: titleSep
- source_contact_id_dts: 203
- internal_contact_id_dts: 203
- ingest_contact_id_dts: 203
- ingest_status_id_dts: 2
- load_contact_id_dts: 345
- load_data_location: '*ict'
- load_status_id_dts: 6
- approve_contact_id_dts: 345
- approve_status_id_dts: 6
- author_id_dts: 203
- note_type_id: 4
- note_text: Loaded with new load_data_proj script
- optional_fields: titleSep
- archive_location_2: ''
- filename_pattern_2: ''
- startdate_pattern_2: ''
- enddate_pattern_2: ''
- format_2: null
- host_2: null
- description: ''
- iso_citation_role: null
- contact_id_codiac: null
- datacite_contributor_type: null
- iso_citation_role_2: null
- contact_id_codiac_2: null
- datacite_contributor_type_2: null
